title: Barrowclift
author: Marc Barrowclift
email: "&#109;&#097;&#114;&#099;&#064;&#098;&#097;&#114;&#114;&#111;&#119;&#099;&#108;&#105;&#102;&#116;&#046;&#109;&#101;"
twitter_username: barrowclift
github_username:  barrowclift
description: Where humanity and computing meet
baseurl: "" # The subpath of your site, e.g. /blog/
dropbox: "https://dropbox.barrowclift.me/assets"
url: https://nitro.barrowclift.me # The base hostname & protocol for your site
host: localhost

permalink: /article/:title # Permalink posts sorted by date with directories is awful.

markdown: kramdown
highlighter: rouge
show_drafts: False
future: False

timezone: America/New_York
locale: en-US

kramdown:
  footnote_backlink: "&#x21A9;&#xFE0E;"

defaults:
  - # POST SPECIFIC VARIABLES
    scope:
      path: "" # empty string for all files
      type: posts # limit to posts
    values:
      viewing_article: true
      has_afterward: false
      share_image: # assume a default post doesn't have an image, /images/assets/${share_image}
  - # SITE-WIDE VARIABLES
    scope:
      path: "" # all files
    values:
      viewing_article: false # *NOT* Being viewed from home, a specific article page
      anchors: true # We want sections to be anchorable by default for everything

plugins:
  - jekyll-feed
  - jemoji